Lab2: functions.c File Reference
functions.c File Reference
#include <stdio.h>
Functions
int athroisma (int x, int y)
int diafora (int x, int y)
void typwsi ()
void typwsi (int a, int b)
int main ()
Function Documentation
athroisma()
int athroisma (int x, int y)
{
        int sum;
        sum = a + b;
        return sum;
}
Referenced by main().
diafora()
int diafora (int x, int y)
{
        int diff;
        diff = a - b;
        return diff;
}
Referenced by main().
main()
int main ()
           {
  /* Dilosi metavlitwn */
  int num1, num2, sum, diff;
  /* Diavasma dedomenwn */
  printf("Tha dwseis dyo akeraious arithmous\n");
  printf("Dwse prwto arithmo: ");
  scanf("%d", &num1);
  printf("Dwse deytero arithmo: ");
  scanf("%d", &num2);
  /* Kalesma synarthsewn - SYMPLHRWSTE ANALOGA  */
  sum = athroisma(num1, num2);
  diff = diafora(num1, num2);
  typwsi(sum, diff);
  return(0);
}
References athroisma(), diafora(), and typwsi().
typwsi() [1/2]
void typwsi ()
Referenced by main().
typwsi() [2/2]
void typwsi (int a, int b)
{
        printf("\nTo athroisma einai %d\n", a);
        printf("\nH diafora einai %d\n", b);
}